server:
  port: 11088
  contextPath: /authserver
  session:
    #超时时间秒
    timeout: 3600
logging:
  config: classpath:log4j2-dev-spring.yml

#spring配置
spring:
  application:
    name: authserver
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://******:3306/******?useUnicode=true&characterEncoding=utf8
      username: ******
      password: ******
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
        maximumPoolSize: 20 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
        minimumIdle:  1 #连接池中允许的最小空闲连接数

  #模版引擎
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: LEGACYHTML5

#mybatis
mybatis:
  mapperLocations: classpath*:com/simonhu/oauth2/*/*/mapper/*Mapper.xml
  typeAliasesPackage: com.simonhu.oauth2

management:
  #关闭安全检测
  security:
    enabled: false
  port: ${server.port}

#监控监控信息设置为非敏感
endpoints:
  health:
    sensitive: false

#站点配置
site:
  #登录密码加盐
  pwdSalt: '******'

smsConfig:
  #发送短信URL
  smsUrl: 'http://******:8061/waii/smsnew/sendSMS'
  #短信商户号
  merchantid: 10001
  #短信签名key
  merchantKey: ******
  #短信验证码有效期
  effectiveTime: 5
  #短信验证码模版
  tempId: JSM40239-0001
  version: 0.1
  #是否验证短信
  validateSMSCode: true
