server:
  port: 11089
  contextPath: /sysmanager
  session:
    timeout: 1800
logging:
  config: classpath:log4j2-dev-spring.yml

#spring配置
spring:
  application:
    name: sysmanager
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://******:3306/******?useUnicode=true&characterEncoding=utf8
      username: ******
      password: ******
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
        maximumPoolSize: 20 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
        minimumIdle:  1 #连接池中允许的最小空闲连接数

  #模版引擎
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: LEGACYHTML5

#mybatis
mybatis:
  mapperLocations: classpath*:com/simonhu/sourcemanager/*/*/mapper/*Mapper.xml
  typeAliasesPackage: com.simonhu.sourcemanager

management:
  #关闭安全检测
  security:
    enabled: false
  port: ${server.port}

#监控监控信息设置为非敏感
endpoints:
  health:
    sensitive: false


#站点配置
site:
  #登录密码加盐
  pwdSalt: '******'
zhxAdmin:
  oauthClient:
    client_id: '1001'
    client_secret: ******
    #请求授权地址(获取code)
    oauth_server_url: http://******:11088/authserver/authorize
    #获取令牌地址（获取accessToken）
    oauth_access_token_url: http://******:11088/authserver/accessToken
    #刷新令牌地址（刷新accessToken，目前系统同未使用，accessToken默认有效期一个小时，服务端依赖于session机制，所以不需要刷新）
    oauth_refresh_access_token_url: http://******:11088/authserver/refreshAccessToken
    #资源服务地址（查询用户信息）
    oauth_user_info_url: http://******:11088/authserver/user/info
    #资源服务地址（查询用户权限列表）
    oauth_user_menu_list_url: http://******:11088/authserver/user/permissions
    #资源服务接口签名key
    oauth_client_sign_key: 123125345234
    #服务端退出地址
    oauth_client_logout_url: http://******:11088/authserver/logout

